### PR TITLE
Added float property support

### PR DESCRIPTION
**Pull request by SkyWriter**
Added support for float properties without need of providing a block for each of them.

### CODE REVIEW

**Comment by SkyWriter** [comment]
Thank you so much. Would you please also release new gem version, just so I can replace GitHub entry in the Gemfile with more generic one?

**Comment by MarkMenard** [comment]
I tried to get to it yesterday, but got boodogled by a failed heating
system I had to deal with. Hopefully today.

Mark

**Comment by SkyWriter** [comment]
You're a superhero! Thank you!

**Comment by MarkMenard** [comment]
You're welcome. I hope it helps with your work. I haven't had a need for
DocWrapper in a long time now.

Mark

**Pull request merged**
